"""Domain models for Data Compass."""

from datacompass.core.models.base import Base, SoftDeleteMixin, TimestampMixin
from datacompass.core.models.catalog_object import CatalogObject
from datacompass.core.models.column import Column
from datacompass.core.models.data_source import DataSource
from datacompass.core.models.dependency import (
    Dependency,
    DependencyResponse,
    ExternalNode,
    LineageEdge,
    LineageGraph,
    LineageNode,
    LineageSummary,
)
from datacompass.core.models.deprecation import (
    CampaignCreate,
    CampaignDetailResponse,
    CampaignImpactSummary,
    CampaignListItem,
    CampaignUpdate,
    Deprecation,
    DeprecationCampaign,
    DeprecationCreate,
    DeprecationHubSummary,
    DeprecationImpact,
    DeprecationResponse,
    DeprecationUpdate,
    ImpactedObject,
)
from datacompass.core.models.dq import (
    BreachDetailResponse,
    BreachResponse,
    BreachStatusUpdate,
    DQBreach,
    DQConfig,
    DQConfigCreate,
    DQConfigDetailResponse,
    DQConfigListItem,
    DQConfigResponse,
    DQConfigUpdate,
    DQExpectation,
    DQExpectationCreate,
    DQExpectationResponse,
    DQExpectationUpdate,
    DQHubSummary,
    DQResult,
    DQResultResponse,
    DQRunResult,
    DQRunResultItem,
    ThresholdConfig,
    YAMLDQConfig,
    YAMLExpectation,
)
from datacompass.core.models.schemas import (
    CatalogObjectDetail,
    CatalogObjectResponse,
    CatalogObjectSummary,
    ColumnResponse,
    ColumnSummary,
    ConnectionTestResult,
    DataSourceCreate,
    DataSourceDetail,
    DataSourceResponse,
    ForeignKeyConstraint,
    ScanResult,
    ScanStats,
    SearchResultResponse,
    SetDescriptionRequest,
    TagRequest,
)
from datacompass.core.models.scheduling import (
    NotificationChannel,
    NotificationChannelCreate,
    NotificationChannelResponse,
    NotificationChannelUpdate,
    NotificationLog,
    NotificationLogResponse,
    NotificationRule,
    NotificationRuleCreate,
    NotificationRuleDetailResponse,
    NotificationRuleResponse,
    NotificationRuleUpdate,
    Schedule,
    ScheduleCreate,
    ScheduleDetailResponse,
    ScheduleResponse,
    ScheduleRun,
    ScheduleRunResponse,
    ScheduleUpdate,
    SchedulerHubSummary,
)
from datacompass.core.models.auth import (
    APIKey,
    APIKeyCreate,
    APIKeyCreated,
    APIKeyResponse,
    AuthStatusResponse,
    LoginRequest,
    RefreshToken,
    RefreshTokenRequest,
    Session,
    TokenResponse,
    User,
    UserCreate,
    UserResponse,
)
from datacompass.core.models.usage import (
    HotTableItem,
    UsageCollectResult,
    UsageHubSummary,
    UsageMetric,
    UsageMetricDetailResponse,
    UsageMetricResponse,
)

__all__ = [
    # SQLAlchemy models
    "Base",
    "TimestampMixin",
    "SoftDeleteMixin",
    "DataSource",
    "CatalogObject",
    "Column",
    "Dependency",
    # Pydantic schemas
    "DataSourceCreate",
    "DataSourceResponse",
    "DataSourceDetail",
    "CatalogObjectResponse",
    "CatalogObjectSummary",
    "CatalogObjectDetail",
    "ColumnResponse",
    "ColumnSummary",
    "ForeignKeyConstraint",
    "ScanResult",
    "ScanStats",
    "ConnectionTestResult",
    # Phase 2 schemas
    "SearchResultResponse",
    "SetDescriptionRequest",
    "TagRequest",
    # Phase 5 schemas (Lineage)
    "DependencyResponse",
    "LineageNode",
    "ExternalNode",
    "LineageEdge",
    "LineageGraph",
    "LineageSummary",
    # Phase 6 schemas (Data Quality)
    "DQConfig",
    "DQExpectation",
    "DQResult",
    "DQBreach",
    "ThresholdConfig",
    "DQConfigCreate",
    "DQConfigUpdate",
    "DQExpectationCreate",
    "DQExpectationUpdate",
    "BreachStatusUpdate",
    "DQConfigResponse",
    "DQConfigListItem",
    "DQConfigDetailResponse",
    "DQExpectationResponse",
    "DQResultResponse",
    "BreachResponse",
    "BreachDetailResponse",
    "DQRunResult",
    "DQRunResultItem",
    "DQHubSummary",
    "YAMLDQConfig",
    "YAMLExpectation",
    # Phase 7 schemas (Deprecation)
    "DeprecationCampaign",
    "Deprecation",
    "CampaignCreate",
    "CampaignUpdate",
    "DeprecationCreate",
    "DeprecationUpdate",
    "CampaignListItem",
    "CampaignDetailResponse",
    "DeprecationResponse",
    "ImpactedObject",
    "DeprecationImpact",
    "CampaignImpactSummary",
    "DeprecationHubSummary",
    # Phase 8 schemas (Scheduling)
    "Schedule",
    "ScheduleRun",
    "NotificationChannel",
    "NotificationRule",
    "NotificationLog",
    "ScheduleCreate",
    "ScheduleUpdate",
    "ScheduleResponse",
    "ScheduleDetailResponse",
    "ScheduleRunResponse",
    "SchedulerHubSummary",
    "NotificationChannelCreate",
    "NotificationChannelUpdate",
    "NotificationChannelResponse",
    "NotificationRuleCreate",
    "NotificationRuleUpdate",
    "NotificationRuleResponse",
    "NotificationRuleDetailResponse",
    "NotificationLogResponse",
    # Phase 9 schemas (Authentication)
    "User",
    "APIKey",
    "Session",
    "RefreshToken",
    "UserCreate",
    "UserResponse",
    "APIKeyCreate",
    "APIKeyResponse",
    "APIKeyCreated",
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "AuthStatusResponse",
    # Usage metrics
    "UsageMetric",
    "UsageMetricResponse",
    "UsageMetricDetailResponse",
    "UsageCollectResult",
    "HotTableItem",
    "UsageHubSummary",
]
